import NavBar from '../components/Nav/Navbar'
import styles from '../styles/Home.module.css'
import Head from 'next/head'

export const Menu = ({children, title}) => { //Parametros que se pasan a la funcion desde el componente principal
  return (
    <div>
      <Head>
        <title>{title} - Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <NavBar/>
      </nav>

      <main className={styles.main}>
        {children}
      </main>
    </div>
  )
}
